name: Lint

on:
  pull_request:
    branches:
    - master
    paths:
    - '**.js'

jobs:
  run-lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here
      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

  deploy-netlify-draft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    needs: run-lint
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

        - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          draft: true
          comment-on-commit: true
