name: Lint

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here
      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
